name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Umożliwia ręczne uruchomienie workflow

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build for Windows
        run: |
          dotnet publish --runtime win-x64 -c Release -o "output/win-x64"

      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-x64-build
          path: output/win-x64

      - name: Create GitHub Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          release_name: "Auto-release"
          files: "output/win-x64/jpgWhiteBorderAdder.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
